name: Build
on:
  push:
    branches-ignore:
      - data
      - gh-pages
    tags:
      - '**'
  pull_request:
    branches-ignore:
      - data
      - gh-pages

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-20.04 # Используем Ubuntu 20.04 для лучшей совместимости с Buildozer
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          architecture: x64

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          repository_root: master
          workdir: test_app
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
          if-no-files-found: error

      - name: Checkout data branch
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          path: data
          ref: data # Ветка data

      - name: Push binary to data branch
        if: github.event_name == 'push'
        run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data bin
